travis:
  secure:
    BINSTAR_TOKEN: kuv538YLBhXjNoksToDlp96LWAOqXBvCsOFr2ptMSsINN08VlnPzGEd6G7pTnAI1EdGpu93tlwS88HSjK9tRSaWYPAcVvTUsSxxjhLJzcYwNlLFc5dDFARWlpJ2gWKyXdwQgWrpIL/egPAr/mQInNJOSi0rLl3xO1PuNFdqywRtcy1rIi7eEiZjbjDjN3RBhv0jaJf9+mAhKLx1Eyr5aqCKLAhi0YZnIcefV+deel/XaFXXDjhK0/+U3k4kEAFzzIKjifOM/ZOzQYV2dofRgdSivK78OpE0xtpV2B/0bLFDBz0P2aMSzSqkQijxXqIV24T3q8TNg/EyvZEnEF5IMcRUftPZXX1GZOIUGwFWThLsb42eVyILzIQYdM3CpMd1JkkUaIYHDrM060ZEQFx4DVBqUGjsSlZSEUHLQ5/Bjv86/bgjvKn1tFHO5J6Y6r/5ShENCzWC0fzHONjInPJJuqfl3JUTw4XknqKW8FDxZo8J4Iy6FSEPbCu3KrkfVfpiiT7U0ATOwcJHXS3aB/miT7BYJRxdPVee8+ixM6l2g9JQYDBx4GKjHb3wpY1enYyIhg9VqF6zn9xYwI00vcN3kWdDEkn0WRO7cbmf4V4IJeYCqUoAn7HwWTdhMXYcUWNxF2ji+30hty2xz0CKjO+QDPkDrm71hCUU7z7FqB7EZnFM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
